apiVersion: v1
kind: Secret
metadata:
  name: postgres-fast-secret
type: Opaque
data:
  POSTGRES_DB: dGFza19hdXRoX2Ri
  POSTGRES_USER: dGFza19hdXRoX3VzZXI=
  POSTGRES_PASSWORD: dGFza19hdXRoX3VzZXIxMjM=
