apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-deployment
  labels:
    app: fast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fast
  template:
    metadata:
      labels:
        app: fast
    spec:
      containers:
      - name: fast
        image: saheerabcd/fast-auth:1.0.4
        ports:
        - containerPort: 8000
        
---     

apiVersion: v1
kind: Service
metadata:
  name: fast-service
spec:
  selector:
    app: fast
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort