apiVersion: apps/v1
kind: Deployment
metadata:
 name: kafka
spec:
 replicas: 1
 selector:
   matchLabels:
     app: kafka
 template:
   metadata:
     labels:
       app: kafka
   spec:
     containers:
     - name: kafka
       image: bitnami/kafka:latest
       ports:
       - containerPort: 9092
       env:
       - name: KAFKA_CFG_ZOOKEEPER_CONNECT
         value: zookeeper:2181
       resources:
          requests:
            memory: "2Gi"  # Adjust based on your requirements
          limits:
            memory: "4Gi"  #   
---
apiVersion: v1
kind: Service
metadata:
 name: kafka
spec:
 selector:
   app: kafka
 ports:
   - protocol: TCP
     port: 9092
     targetPort: 9092
