apiVersion: v1
kind: Secret
metadata:
  name: celery-secret
type: Opaque
data:
  CELERY_BROKER_URL: cHlhbXFwOi8vdXNlcjo5ekg1RmVPcTNYOHpicUl6QG5ldy1hcHAtcmFiYml0bXE6NTY3Mi8v
  CELERY_RESULT_BACKEND: cnBjOi8v